### ISSUE TITLE
RecycleApp error

### ISSUE THREAD

**Issue by sammyke007** [pippyn/Home-Assistant-Sensor-Afvalbeheer#322]
Since today I receive this message in the logs:
Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='recycleapp.be', port=443): Max retries exceeded with url: /api/app/v1/access-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efe87dd3be0>: Failed to establish a new connection: [Errno -3] Try again'))"))

The sensors show "Onbekend" (Unknown)

**Comment by madradrakie** [comment]
same problem here. I already restarted home assistant and everything but no result. Status unknown

**Comment by M0nty99** [comment]
Same happened to me. restarting HA also no result 

Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='recycleapp.be', port=443): Max retries exceeded with url: /api/app/v1/access-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xee8128e0>: Failed to establish a new connection: [Errno -3] Try again'))"))

**Comment by yornola** [comment]
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:1244
Integration: afvalbeheer (documentation)
First occurred: 07:25:15 (1 occurrences)
Last logged: 07:25:15

Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='recycleapp.be', port=443): Max retries exceeded with url: /api/app/v1/access-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb27dd340>: Failed to establish a new connection: [Errno -3] Try again'))"))

**Comment by pippyn** [comment]
same issue as #321
