### ISSUE TITLE
think suffix: needs "" if not a empty?

### ISSUE THREAD

**Issue by ldijkman** [pippyn/Home-Assistant-Sensor-Afvalbeheer#404]
maybe im wrong but

think suffix: needs "" if not a empty?
suffix: a
suffix: ""
suffix:                gives error
maybe a note in the readme md
or #comment in the example config

suffix: a                        # (optional)    if empty       suffix: ""

![2023-05-31-175539_1920x1080_scrot](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/45427770/fac6f49c-bbcf-4c76-9f27-f04adcb05138)

![2023-05-31-175731_1920x1080_scrot](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/45427770/8cf4cd41-df85-4354-a8f6-14fc42d1c191)

**Comment by ldijkman** [comment]
if i do 
suffix:
i get on restart an error see image 
sufix: "" 
is working ok
![2023-06-01-164840_1920x1080_scrot](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/assets/45427770/4379465c-371d-40ad-8b12-24bac7ed3dd5)

**Comment by SVD-NL** [comment]
I found where this issue originates from:

In `PLATFORM_SCHEMA` the type is set to `cv.string`
https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/blob/f31deca970f33a1ab8fbcb954fe106efb92f5cba/custom_components/afvalbeheer/const.py#L43C9-L43C58

This is the method being used to validate that:
https://github.com/home-assistant/core/blob/e4a7c57b81f0e8ae0800cc674b55491def70562a/homeassistant/helpers/config_validation.py#L567C4-L567C4

It explicitly returns that error when the value is None.
This also why you need an empty string as default value, it'll return an error if you don't.
This is expected behavior.

I don't think this is something that's possible to solve (without removing input validation, but i doubt that's an option).
For optional values you're generally going to leave it out of the config, or include it with the default value if you don't want to set it. Leaving it empty is going to cause errors in every integration using input validation (which should be every integration).

If you believe this is an issue, it'll need to be changed by home assistant, not this integration.

**Comment by pippyn** [comment]
@SVD-NL is right. I'm going to close this issue.
